<a href="https://colab.research.google.com/github/junwoochoi33/NLPPractice/blob/main/nlp_01_practice_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. 정수 인코딩

In [12]:
text = """
Artificial intelligence (AI) is transforming the modern world across various industries.
From autonomous vehicles and virtual assistants to fraud detection systems and medical diagnostics, AI is being integrated into everyday technologies.
At its core, AI involves machines that can perform tasks typically requiring human intelligence, such as learning, reasoning, and decision-making.
Recent advances in deep learning, a subfield of machine learning, have enabled significant improvements in image recognition, natural language processing, and robotics.
As AI systems continue to evolve, questions surrounding ethics, bias, and transparency are becoming increasingly important for researchers and developers.
"""

In [13]:
text

'\nArtificial intelligence (AI) is transforming the modern world across various industries. \nFrom autonomous vehicles and virtual assistants to fraud detection systems and medical diagnostics, AI is being integrated into everyday technologies. \nAt its core, AI involves machines that can perform tasks typically requiring human intelligence, such as learning, reasoning, and decision-making. \nRecent advances in deep learning, a subfield of machine learning, have enabled significant improvements in image recognition, natural language processing, and robotics. \nAs AI systems continue to evolve, questions surrounding ethics, bias, and transparency are becoming increasingly important for researchers and developers.\n'

In [14]:
from nltk.tokenize import sent_tokenize

In [15]:
import nltk
nltk.download('punkt_tab')

sent_text = sent_tokenize(text)
sent_text

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


['\nArtificial intelligence (AI) is transforming the modern world across various industries.',
 'From autonomous vehicles and virtual assistants to fraud detection systems and medical diagnostics, AI is being integrated into everyday technologies.',
 'At its core, AI involves machines that can perform tasks typically requiring human intelligence, such as learning, reasoning, and decision-making.',
 'Recent advances in deep learning, a subfield of machine learning, have enabled significant improvements in image recognition, natural language processing, and robotics.',
 'As AI systems continue to evolve, questions surrounding ethics, bias, and transparency are becoming increasingly important for researchers and developers.']

In [18]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [23]:
vocabulary = {}
sentences = []
stop_words = stopwords.words('english')

for sent in sent_text:
  sentence = word_tokenize(sent)
  result = []

  for word in sentence:
    word = word.lower()
    if (word not in stop_words) and (len(word) > 2):
      result.append(word)
      if word not in vocabulary:
        vocabulary[word] = 0
      vocabulary[word] += 1

  sentences.append(result)

In [24]:
print(sentences)

[['artificial', 'intelligence', 'transforming', 'modern', 'world', 'across', 'various', 'industries'], ['autonomous', 'vehicles', 'virtual', 'assistants', 'fraud', 'detection', 'systems', 'medical', 'diagnostics', 'integrated', 'everyday', 'technologies'], ['core', 'involves', 'machines', 'perform', 'tasks', 'typically', 'requiring', 'human', 'intelligence', 'learning', 'reasoning', 'decision-making'], ['recent', 'advances', 'deep', 'learning', 'subfield', 'machine', 'learning', 'enabled', 'significant', 'improvements', 'image', 'recognition', 'natural', 'language', 'processing', 'robotics'], ['systems', 'continue', 'evolve', 'questions', 'surrounding', 'ethics', 'bias', 'transparency', 'becoming', 'increasingly', 'important', 'researchers', 'developers']]


In [26]:
print(vocabulary)

{'artificial': 1, 'intelligence': 2, 'transforming': 1, 'modern': 1, 'world': 1, 'across': 1, 'various': 1, 'industries': 1, 'autonomous': 1, 'vehicles': 1, 'virtual': 1, 'assistants': 1, 'fraud': 1, 'detection': 1, 'systems': 2, 'medical': 1, 'diagnostics': 1, 'integrated': 1, 'everyday': 1, 'technologies': 1, 'core': 1, 'involves': 1, 'machines': 1, 'perform': 1, 'tasks': 1, 'typically': 1, 'requiring': 1, 'human': 1, 'learning': 3, 'reasoning': 1, 'decision-making': 1, 'recent': 1, 'advances': 1, 'deep': 1, 'subfield': 1, 'machine': 1, 'enabled': 1, 'significant': 1, 'improvements': 1, 'image': 1, 'recognition': 1, 'natural': 1, 'language': 1, 'processing': 1, 'robotics': 1, 'continue': 1, 'evolve': 1, 'questions': 1, 'surrounding': 1, 'ethics': 1, 'bias': 1, 'transparency': 1, 'becoming': 1, 'increasingly': 1, 'important': 1, 'researchers': 1, 'developers': 1}


In [27]:
sorted_vocabulary = sorted(vocabulary.items(), key = lambda x:x[1], reverse=True)
print(sorted_vocabulary)

[('learning', 3), ('intelligence', 2), ('systems', 2), ('artificial', 1), ('transforming', 1), ('modern', 1), ('world', 1), ('across', 1), ('various', 1), ('industries', 1), ('autonomous', 1), ('vehicles', 1), ('virtual', 1), ('assistants', 1), ('fraud', 1), ('detection', 1), ('medical', 1), ('diagnostics', 1), ('integrated', 1), ('everyday', 1), ('technologies', 1), ('core', 1), ('involves', 1), ('machines', 1), ('perform', 1), ('tasks', 1), ('typically', 1), ('requiring', 1), ('human', 1), ('reasoning', 1), ('decision-making', 1), ('recent', 1), ('advances', 1), ('deep', 1), ('subfield', 1), ('machine', 1), ('enabled', 1), ('significant', 1), ('improvements', 1), ('image', 1), ('recognition', 1), ('natural', 1), ('language', 1), ('processing', 1), ('robotics', 1), ('continue', 1), ('evolve', 1), ('questions', 1), ('surrounding', 1), ('ethics', 1), ('bias', 1), ('transparency', 1), ('becoming', 1), ('increasingly', 1), ('important', 1), ('researchers', 1), ('developers', 1)]


In [29]:
integer_embedding = {}
i = 0
for (word, frequency) in sorted_vocabulary:
  if frequency > 1:
    i = i + 1
    integer_embedding[word] = i

In [30]:
print(integer_embedding)

{'learning': 1, 'intelligence': 2, 'systems': 3}


In [31]:
# oov: out of vocabulary
integer_embedding['oov'] = len(integer_embedding) + 1
print(integer_embedding)

{'learning': 1, 'intelligence': 2, 'systems': 3, 'oov': 4}


In [32]:
encoded = []
for s in sentences:
  temp = []
  for w in s:
    try:
      temp.append(integer_embedding[w])
    except KeyError:
      temp.append(integer_embedding['oov'])
  encoded.append(temp)

print(encoded)


[[4, 2, 4, 4, 4, 4, 4, 4], [4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4], [4, 4, 4, 4, 4, 4, 4, 4, 2, 1, 4, 4], [4, 4, 4, 1, 4, 4, 1, 4, 4, 4, 4, 4, 4, 4, 4, 4], [3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]]


In [34]:
import numpy as np
from collections import Counter

In [36]:
print(sentences)

[['artificial', 'intelligence', 'transforming', 'modern', 'world', 'across', 'various', 'industries'], ['autonomous', 'vehicles', 'virtual', 'assistants', 'fraud', 'detection', 'systems', 'medical', 'diagnostics', 'integrated', 'everyday', 'technologies'], ['core', 'involves', 'machines', 'perform', 'tasks', 'typically', 'requiring', 'human', 'intelligence', 'learning', 'reasoning', 'decision-making'], ['recent', 'advances', 'deep', 'learning', 'subfield', 'machine', 'learning', 'enabled', 'significant', 'improvements', 'image', 'recognition', 'natural', 'language', 'processing', 'robotics'], ['systems', 'continue', 'evolve', 'questions', 'surrounding', 'ethics', 'bias', 'transparency', 'becoming', 'increasingly', 'important', 'researchers', 'developers']]


In [40]:
words = np.hstack(sentences)
print(words)

['artificial' 'intelligence' 'transforming' 'modern' 'world' 'across'
 'various' 'industries' 'autonomous' 'vehicles' 'virtual' 'assistants'
 'fraud' 'detection' 'systems' 'medical' 'diagnostics' 'integrated'
 'everyday' 'technologies' 'core' 'involves' 'machines' 'perform' 'tasks'
 'typically' 'requiring' 'human' 'intelligence' 'learning' 'reasoning'
 'decision-making' 'recent' 'advances' 'deep' 'learning' 'subfield'
 'machine' 'learning' 'enabled' 'significant' 'improvements' 'image'
 'recognition' 'natural' 'language' 'processing' 'robotics' 'systems'
 'continue' 'evolve' 'questions' 'surrounding' 'ethics' 'bias'
 'transparency' 'becoming' 'increasingly' 'important' 'researchers'
 'developers']


In [42]:
vocabulary = Counter(words)
print(vocabulary)

Counter({np.str_('learning'): 3, np.str_('intelligence'): 2, np.str_('systems'): 2, np.str_('artificial'): 1, np.str_('transforming'): 1, np.str_('modern'): 1, np.str_('world'): 1, np.str_('across'): 1, np.str_('various'): 1, np.str_('industries'): 1, np.str_('autonomous'): 1, np.str_('vehicles'): 1, np.str_('virtual'): 1, np.str_('assistants'): 1, np.str_('fraud'): 1, np.str_('detection'): 1, np.str_('medical'): 1, np.str_('diagnostics'): 1, np.str_('integrated'): 1, np.str_('everyday'): 1, np.str_('technologies'): 1, np.str_('core'): 1, np.str_('involves'): 1, np.str_('machines'): 1, np.str_('perform'): 1, np.str_('tasks'): 1, np.str_('typically'): 1, np.str_('requiring'): 1, np.str_('human'): 1, np.str_('reasoning'): 1, np.str_('decision-making'): 1, np.str_('recent'): 1, np.str_('advances'): 1, np.str_('deep'): 1, np.str_('subfield'): 1, np.str_('machine'): 1, np.str_('enabled'): 1, np.str_('significant'): 1, np.str_('improvements'): 1, np.str_('image'): 1, np.str_('recognition'): 

In [45]:
vocab_size = 2
common_vocabulary = vocabulary.most_common(vocab_size)
print(common_vocabulary)

[(np.str_('learning'), 3), (np.str_('intelligence'), 2)]


In [48]:
integer_embedding = {}
i = 0
for (word, frequency) in common_vocabulary:
    i += 1
    integer_embedding[word] = i

print(integer_embedding)


{np.str_('learning'): 1, np.str_('intelligence'): 2}


In [50]:
from nltk import FreqDist

In [52]:
vocabulary = FreqDist(np.hstack(sentences))
print(vocabulary)

<FreqDist with 57 samples and 61 outcomes>


In [53]:
vocab_size = 2
common_vocabulary = vocabulary.most_common(vocab_size)
print(common_vocabulary)

[(np.str_('learning'), 3), (np.str_('intelligence'), 2)]


In [54]:
integer_embedding = {word[0] : index + 1 for index, word in enumerate(common_vocabulary)}
print(integer_embedding)

{np.str_('learning'): 1, np.str_('intelligence'): 2}


In [55]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [56]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

In [57]:
tokenizer.word_index

{'learning': 1,
 'intelligence': 2,
 'systems': 3,
 'artificial': 4,
 'transforming': 5,
 'modern': 6,
 'world': 7,
 'across': 8,
 'various': 9,
 'industries': 10,
 'autonomous': 11,
 'vehicles': 12,
 'virtual': 13,
 'assistants': 14,
 'fraud': 15,
 'detection': 16,
 'medical': 17,
 'diagnostics': 18,
 'integrated': 19,
 'everyday': 20,
 'technologies': 21,
 'core': 22,
 'involves': 23,
 'machines': 24,
 'perform': 25,
 'tasks': 26,
 'typically': 27,
 'requiring': 28,
 'human': 29,
 'reasoning': 30,
 'decision-making': 31,
 'recent': 32,
 'advances': 33,
 'deep': 34,
 'subfield': 35,
 'machine': 36,
 'enabled': 37,
 'significant': 38,
 'improvements': 39,
 'image': 40,
 'recognition': 41,
 'natural': 42,
 'language': 43,
 'processing': 44,
 'robotics': 45,
 'continue': 46,
 'evolve': 47,
 'questions': 48,
 'surrounding': 49,
 'ethics': 50,
 'bias': 51,
 'transparency': 52,
 'becoming': 53,
 'increasingly': 54,
 'important': 55,
 'researchers': 56,
 'developers': 57}

In [58]:
tokenizer.word_counts

OrderedDict([('artificial', 1),
             ('intelligence', 2),
             ('transforming', 1),
             ('modern', 1),
             ('world', 1),
             ('across', 1),
             ('various', 1),
             ('industries', 1),
             ('autonomous', 1),
             ('vehicles', 1),
             ('virtual', 1),
             ('assistants', 1),
             ('fraud', 1),
             ('detection', 1),
             ('systems', 2),
             ('medical', 1),
             ('diagnostics', 1),
             ('integrated', 1),
             ('everyday', 1),
             ('technologies', 1),
             ('core', 1),
             ('involves', 1),
             ('machines', 1),
             ('perform', 1),
             ('tasks', 1),
             ('typically', 1),
             ('requiring', 1),
             ('human', 1),
             ('learning', 3),
             ('reasoning', 1),
             ('decision-making', 1),
             ('recent', 1),
             ('advances', 1),
 

In [61]:
integer_encoding = tokenizer.texts_to_sequences(sentences)

## 2. 패딩 작업

In [62]:
print(integer_encoding)

[[4, 2, 5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15, 16, 3, 17, 18, 19, 20, 21], [22, 23, 24, 25, 26, 27, 28, 29, 2, 1, 30, 31], [32, 33, 34, 1, 35, 36, 1, 37, 38, 39, 40, 41, 42, 43, 44, 45], [3, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]]


In [64]:
max_len = max(len(encode) for encode in integer_encoding)
print(max_len)

16


In [68]:
for encode in integer_encoding:
  while len(encode) < max_len:
    encode.append(0)

padding = np.array(integer_encoding)
print(padding)

[[ 4  2  5  6  7  8  9 10  0  0  0  0  0  0  0  0]
 [11 12 13 14 15 16  3 17 18 19 20 21  0  0  0  0]
 [22 23 24 25 26 27 28 29  2  1 30 31  0  0  0  0]
 [32 33 34  1 35 36  1 37 38 39 40 41 42 43 44 45]
 [ 3 46 47 48 49 50 51 52 53 54 55 56 57  0  0  0]]


In [69]:
integer_encoding = tokenizer.texts_to_sequences(sentences)

In [71]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padding = pad_sequences(integer_encoding)
print(padding)

[[ 0  0  0  0  0  0  0  0  4  2  5  6  7  8  9 10]
 [ 0  0  0  0 11 12 13 14 15 16  3 17 18 19 20 21]
 [ 0  0  0  0 22 23 24 25 26 27 28 29  2  1 30 31]
 [32 33 34  1 35 36  1 37 38 39 40 41 42 43 44 45]
 [ 0  0  0  3 46 47 48 49 50 51 52 53 54 55 56 57]]


In [75]:
padding = pad_sequences(integer_encoding, padding='post', maxlen=16, value=-1)
print(padding)

[[ 4  2  5  6  7  8  9 10 -1 -1 -1 -1 -1 -1 -1 -1]
 [11 12 13 14 15 16  3 17 18 19 20 21 -1 -1 -1 -1]
 [22 23 24 25 26 27 28 29  2  1 30 31 -1 -1 -1 -1]
 [32 33 34  1 35 36  1 37 38 39 40 41 42 43 44 45]
 [ 3 46 47 48 49 50 51 52 53 54 55 56 57 -1 -1 -1]]


## 3. TF-IDF

In [76]:
documents = [
    "배가 너무 너무 아프다",
    "배가 너무 고프다",
    "저기 저기 배가 지나간다",
    "비가 와서 다리가 아프다"
]

In [77]:
vocabulary = list(set(w for doc in documents for w in doc.split()))

In [78]:
print(vocabulary)

['배가', '비가', '아프다', '고프다', '와서', '너무', '지나간다', '저기', '다리가']


In [79]:
import math

In [80]:
num_documents = len(documents)

In [81]:
def tf(t, d):
  return d.count(t)

In [83]:
def idf(t):
  df = 0
  for doc in documents:
    df += t in doc
  return math.log(num_documents / (df+1))

In [84]:
def tfidf(t, d):
  return tf(t, d) * idf(t)

In [87]:
import pandas as pd

result = []
for i in range(num_documents):
  result.append([])
  d = documents[i]
  for j in range(len(vocabulary)):
    t = vocabulary[j]
    result[-1].append(tf(t, d))

term_frequency = pd.DataFrame(result, columns=vocabulary)
term_frequency

배가  비가  아프다  고프다  와서  너무  지나간다  저기  다리가
0   1   0    1    0   0   2     0   0    0
1   1   0    0    1   0   1     0   0    0
2   1   0    0    0   0   0     1   2    0
3   0   1    1    0   1   0     0   0    1

In [88]:
result = []
for j in range(len(vocabulary)):
  t = vocabulary[j]
  result.append(idf(t))

inverse_df = pd.DataFrame(result, index=vocabulary, columns=["IDF"])
inverse_df

IDF
배가    0.000000
비가    0.693147
아프다   0.287682
고프다   0.693147
와서    0.693147
너무    0.287682
지나간다  0.693147
저기    0.693147
다리가   0.693147

In [89]:
result = []
for i in range(num_documents):
  result.append([])
  d = documents[i]
  for j in range(len(vocabulary)):
    t = vocabulary[j]
    result[-1].append(tfidf(t, d))

tf_idf = pd.DataFrame(result, columns=vocabulary)
tf_idf

배가        비가       아프다       고프다  ...        너무      지나간다        저기       다리가
0  0.0  0.000000  0.287682  0.000000  ...  0.575364  0.000000  0.000000  0.000000
1  0.0  0.000000  0.000000  0.693147  ...  0.287682  0.000000  0.000000  0.000000
2  0.0  0.000000  0.000000  0.000000  ...  0.000000  0.693147  1.386294  0.000000
3  0.0  0.693147  0.287682  0.000000  ...  0.000000  0.000000  0.000000  0.693147

[4 rows x 9 columns]